# Generated by Django 4.0.10 on 2023-03-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_code', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('ean_sku', models.CharField(max_length=15)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('ean', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('store_code', models.CharField(max_length=10)),
                ('store_name', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('store_advisor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrinter',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_terminal', models.CharField(max_length=20)),
                ('ip_printer', models.CharField(max_length=15)),
            ],
        ),
    ]
