# Generated by Django 4.0.10 on 2023-03-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('lisa_number', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('approved', models.IntegerField()),
                ('total_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('lisa_number', models.IntegerField()),
                ('picking_number', models.IntegerField()),
                ('ean_store', models.CharField(max_length=15)),
                ('ean_sku', models.CharField(max_length=15)),
                ('sku', models.CharField(max_length=30)),
                ('quantity_to_collect', models.IntegerField()),
                ('quantity_inventoried', models.IntegerField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_app.orderstatus')),
                ('user_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_app.userprinter')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=30)),
                ('order_number', models.IntegerField()),
                ('lisa_number', models.IntegerField()),
                ('box_number', models.CharField(max_length=20)),
                ('ean_sku', models.CharField(max_length=30)),
                ('sku', models.CharField(max_length=30)),
                ('quantity_Shipped', models.IntegerField()),
                ('quantity_ordered', models.IntegerField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('ean_store', models.CharField(max_length=30)),
                ('customer_code', models.IntegerField()),
                ('customer_nit', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=30)),
                ('address_delivery', models.CharField(max_length=50)),
                ('city_delivery', models.CharField(max_length=30)),
                ('ean_sbd', models.CharField(max_length=20)),
                ('nit_sbd', models.CharField(max_length=20)),
                ('sbd_address', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=30)),
                ('order_confirmation', models.CharField(max_length=20)),
                ('order_date_lisa', models.DateField()),
                ('order_closing_date', models.DateField()),
                ('ean_customer', models.CharField(max_length=20)),
                ('customer_destination', models.CharField(max_length=20)),
                ('total_weight', models.FloatField()),
                ('total_volume', models.FloatField()),
                ('order_opening_date_lds', models.DateField()),
                ('order_closing_date_lds', models.DateField()),
                ('status_order', models.CharField(max_length=20)),
                ('number_of_prints', models.IntegerField()),
                ('printing_format', models.TextField()),
                ('remision_number', models.IntegerField()),
                ('printer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_app.userprinter')),
            ],
        ),
    ]
